In [2]:
# Run this if facing issue with transformers
# pip install torch torchvision torchaudio transformers

import torch
from datasets import Dataset
from scipy.stats import loguniform
import optuna
from transformers import TrainingArguments, Trainer, AutoTokenizer, AutoModelForSequenceClassification, pipeline, BertForSequenceClassification, BertTokenizer
import torch

from Utils.import_packages import *

In [3]:
train_df = pd.read_csv('Data/train_labelled.csv')
val_df = pd.read_csv('Data/val_labelled.csv')
test_df = pd.read_csv('Data/test_labelled.csv')

In [12]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

ind = []
for i, s in enumerate(train_df["title"].tolist()):
    scores = analyzer.polarity_scores(s)
    if scores["neu"] == max(scores["neg"], scores["neu"], scores["pos"]):
        ind += [i]
train_df = train_df.drop(index=ind)
print(train_df.shape)

ind = []
for i, s in enumerate(val_df["title"].tolist()):
    scores = analyzer.polarity_scores(s)
    if scores["neu"] == max(scores["neg"], scores["neu"], scores["pos"]):
        ind += [i]
val_df = val_df.drop(index=ind)
print(val_df.shape)

ind = []
for i, s in enumerate(test_df["title"].tolist()):
    scores = analyzer.polarity_scores(s)
    if scores["neu"] == max(scores["neg"], scores["neu"], scores["pos"]):
        ind += [i]

test_df = test_df.drop(index=ind)
print(test_df.shape)

(825, 6)
(46, 6)
(390, 6)

In [13]:
# Apply preprocessing to datasets
train_df["title"] = train_df["title"].str.replace(r'\([A-Za-z]+:[A-Za-z]+\)', '', regex=True)
val_df["title"] = val_df["title"].str.replace(r'\([A-Za-z]+:[A-Za-z]+\)', '', regex=True)
test_df["title"] = test_df["title"].str.replace(r'\([A-Za-z]+:[A-Za-z]+\)', '', regex=True)

train_df["title"] = train_df["title"].apply(lambda text: re.sub(r"\s+", " ", text).strip())
val_df["title"] = val_df["title"].apply(lambda text: re.sub(r"\s+", " ", text).strip())
test_df["title"] = test_df["title"].apply(lambda text: re.sub(r"\s+", " ", text).strip())

train_df = train_df.sort_values(by="date")
val_df = val_df.sort_values(by="date")
test_df = test_df.sort_values(by="date")

In [14]:
# Check distribution of labels
print(train_df['sentiment_label'].value_counts())
print(val_df['sentiment_label'].value_counts())
print(test_df['sentiment_label'].value_counts())

sentiment_label
1    414
0    411
Name: count, dtype: int64
sentiment_label
1    23
0    23
Name: count, dtype: int64
sentiment_label
0    255
1    135
Name: count, dtype: int64

# BERT and FinBERT
BERT and FinBERT are a pre-trained text analysis models, with Finbert particularly trained on financial data. It labels financial data as either "positive", "neutral" or "negative" by assigning a probability to each class, and return the class with the highest probability.
<br> For our use case, we labelled sentiments using only '1' or '0' for the excess 3 day aggregated returns.
<br> For BERT, we will fit the model directly on our test set, since it is pre-trained, just to see how it performs as a baseline compared to FinBERT. This is done by predicting the 3 sentiment probabilities, then using them to map to 1 or 0 based on whether P(positive) >  P(negative)
<BR> For FinBERT, we will first fine tune finBERT to label using 2 classifications on our training set, then using Optuna to search for the best parameters that will return the model with the highest F1 by evaluating its performance on the valuation set. This fine tuned model is then fitted to test set and sentiment labels are predicted again based on the similar mapping logic as before.

## BERT
### Fitting on Test Set

In [16]:
# Device setup
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# Load the saved model and tokenizer
model = AutoModelForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=3).to(device)
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model.eval()

# Preprocessing function for BERT
def preprocess_text(text_list):
    return [text.strip().lower() for text in text_list]

# Tokenize data
def preprocess_data(example):
    processed_texts = preprocess_text(example['title'])
    return tokenizer(processed_texts, padding='max_length', truncation=True, max_length=128)

# Tokenize the test set using the saved tokenizer
test_tokenized_df = Dataset.from_pandas(test_df).map(preprocess_data, batched=True)
test_tokenized_df = test_tokenized_df.rename_column("sentiment_label", "labels")
test_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Run predictions on the test set
all_logits = []
with torch.no_grad():
    for batch in torch.utils.data.DataLoader(test_tokenized_df, batch_size=8):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        all_logits.append(logits.cpu())

logits = torch.cat(all_logits, dim=0)
probabilities = torch.softmax(logits, dim=1).cpu().numpy()

prob_negative = probabilities[:, 1]
prob_neutral = probabilities[:, 2]
prob_positive = probabilities[:, 0]

predicted_labels = [
    1 if prob_positive > max(prob_negative, prob_neutral) else 0
    for prob_negative, prob_neutral, prob_positive in zip(prob_negative, prob_neutral, prob_positive)
]

# Save predictions to test DataFrame
test_df_results_bert = test_df.copy()
test_df_results_bert['prob_negative'] = prob_negative
test_df_results_bert['prob_neutral'] = prob_neutral
test_df_results_bert['prob_positive'] = prob_positive
test_df_results_bert['finbert_sentiment_labels'] = predicted_labels

# Evaluate metrics if ground-truth labels exist
if 'sentiment_label' in test_df_results_bert.columns:
    precision, recall, f1, _ = precision_recall_fscore_support(
        test_df_results_bert['sentiment_label'], predicted_labels, average='weighted'
    )
    accuracy = accuracy_score(test_df_results_bert['sentiment_label'], predicted_labels)

    print(f"Test Accuracy: {accuracy}")
    print(f"Test Precision: {precision}")
    print(f"Test Recall: {recall}")
    print(f"Test F1-Score: {f1}")

test_df_results_bert

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/390 [00:00<?, ? examples/s]

Test Accuracy: 0.6538461538461539
Test Precision: 0.42751479289940825
Test Recall: 0.6538461538461539
Test F1-Score: 0.516994633273703

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

,title,source,topic,company name(s) - cleaned,date,sentiment_label,prob_negative,prob_neutral,prob_positive,finbert_sentiment_labels
58421,Visa Reimagines Customer Loyalty with New Web3...,Business Wire,Transaction and Payment Processing Services,Visa Inc.,2024-01-04,1,0.219881,0.481068,0.299052,0
43862,True Potential Appoints Northern Trust for Ass...,Business Wire,Asset Management and Custody Banks,Northern Trust Corporation,2024-01-19,0,0.225078,0.475394,0.299528,0
60612,Wells Fargo & Company Approves and Adopts the ...,SEC Form 8k,Diversified Banks,Wells Fargo & Company,2024-01-24,1,0.212528,0.512595,0.274877,0
642,Abbott Laboratories Enters into Five Year Cred...,SEC Form 8k,Health Care Equipment,Abbott Laboratories,2024-01-29,1,0.211281,0.505997,0.282722,0
35225,Leidos Wins Contract to Support Advanced Resea...,PR Newswire,Research and Consulting Services,"Leidos Holdings, Inc.",2024-01-29,0,0.227047,0.477124,0.295828,0
...,...,...,...,...,...,...,...,...,...,...
31428,What s More Wicked than the Crime of,https://mises.org/podcasts/human-action-podcas...,economics,NaN,2024-12-13,0,0.246392,0.432421,0.321187,0
3589,Nice for them nice for your wallet,https://www.komando.com/tips/nice-for-them-nic...,tech,NaN,2024-12-13,0,0.258311,0.421892,0.319798,0
35218,The Missing Secret,https://mises.org/friday-philosophy/missing-se...,economics,NaN,2024-12-13,0,0.240583,0.427770,0.331647,0
21538,What s More Wicked than the Crime of,https://mises.org/podcasts/human-action-podcas...,economics,NaN,2024-12-13,0,0.246392,0.432421,0.321187,0
21356,The Missing Secret,https://mises.org/friday-philosophy/missing-se...,economics,NaN,2024-12-13,0,0.240583,0.427770,0.331647,0

In [18]:
test_df_results_bert.to_csv('results/test_df_results_bert_filtered.csv', index=False)

## Prosus AI/FinBERT
### Optuna Hyperparameter Optimisation

In [19]:
train_subset_size = int(len(train_df) * 0.05) # take 5% of train set

# Sample proportionally across all dates
train_subset_df = train_df.iloc[::len(train_df) // train_subset_size]
train_subset_df = train_subset_df.sort_values(by=['date']).reset_index(drop=True)

In [20]:
# Device setup
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("ProsusAI/finbert")

# Tokenize data
def preprocess_data(example):
    return tokenizer(example['title'], padding='max_length', max_length=128, truncation=True)

train_subset_tokenized_df = Dataset.from_pandas(train_subset_df).map(preprocess_data, batched=True)
train_subset_tokenized_df = train_subset_tokenized_df.rename_column("sentiment_label", "labels")
train_subset_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

val_tokenized_df = Dataset.from_pandas(val_df).map(preprocess_data, batched=True)
val_tokenized_df = val_tokenized_df.rename_column("sentiment_label", "labels")
val_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Define metrics for evaluation
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    probabilities = torch.nn.functional.softmax(torch.tensor(logits), dim=-1).numpy()

    prob_negative = probabilities[:, 1]
    prob_neutral = probabilities[:, 2]
    prob_positive = probabilities[:, 0]

    predicted_labels = [
    1 if prob_positive > max(prob_negative, prob_neutral) else 0
    for prob_negative, prob_neutral, prob_positive in zip(prob_negative, prob_neutral, prob_positive)
]

    precision, recall, f1, _ = precision_recall_fscore_support(labels, predicted_labels, average='weighted')
    accuracy = accuracy_score(labels, predicted_labels)

    return {
        'accuracy': accuracy,
        'precision': precision,
        'recall': recall,
        'f1': f1
    }

# Define the Optuna objective function
def objective(trial):
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
    batch_size = trial.suggest_categorical('batch_size', [8, 16, 32])
    num_train_epochs = trial.suggest_int('num_train_epochs', 2, 5)

    # Load model
    model = AutoModelForSequenceClassification.from_pretrained('ProsusAI/finbert', num_labels=3).to(device)

    # Define training arguments
    training_args = TrainingArguments(
        output_dir="./train_subset_results",
        eval_strategy="epoch",
        learning_rate=learning_rate,
        per_device_train_batch_size=batch_size,
        num_train_epochs=num_train_epochs,
        weight_decay=0.01,
        save_strategy="epoch",
        logging_dir="./train_subset_logs",
        logging_steps=10,
        disable_tqdm=False,
        load_best_model_at_end=True
    )

    # Define the Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_subset_tokenized_df,
        eval_dataset=val_tokenized_df,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics
    )

    # Train model
    trainer.train()

    # Evaluate model
    eval_results = trainer.evaluate()
    return eval_results['eval_f1']

# Initialize an Optuna study
study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=50)

# Output the best hyperparameters
print("Best hyperparameters:")
print(study.best_params)

Using device: cuda

Map:   0%|          | 0/42 [00:00<?, ? examples/s]

Map:   0%|          | 0/46 [00:00<?, ? examples/s]

[I 2024-12-17 23:43:15,012] A new study created in memory with name: no-name-c508629f-19de-4799-98c9-4faaf3745192
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:21,912] Trial 0 finished with value: 0.5867612293144208 and parameters: {'learning_rate': 1.0322477572886013e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 0 with value: 0.5867612293144208.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:29,984] Trial 1 finished with value: 0.6515151515151515 and parameters: {'learning_rate': 1.3136056578820714e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:34,564] Trial 2 finished with value: 0.5208333333333333 and parameters: {'learning_rate': 1.0814706758571704e-05, 'batch_size': 32, 'num_train_epochs': 2}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:42,739] Trial 3 finished with value: 0.47727272727272724 and parameters: {'learning_rate': 3.257684671115304e-05, 'batch_size': 8, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:47,273] Trial 4 finished with value: 0.5820181731229077 and parameters: {'learning_rate': 2.4437218547361645e-05, 'batch_size': 32, 'num_train_epochs': 2}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:55,111] Trial 5 finished with value: 0.5334685598377282 and parameters: {'learning_rate': 2.1668757659640132e-05, 'batch_size': 16, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:43:59,674] Trial 6 finished with value: 0.6079545454545455 and parameters: {'learning_rate': 2.2446272630136936e-05, 'batch_size': 32, 'num_train_epochs': 2}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:05,472] Trial 7 finished with value: 0.5516569200779727 and parameters: {'learning_rate': 3.834279533035224e-05, 'batch_size': 16, 'num_train_epochs': 3}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:11,313] Trial 8 finished with value: 0.5820181731229077 and parameters: {'learning_rate': 2.525171891863549e-05, 'batch_size': 8, 'num_train_epochs': 3}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:16,025] Trial 9 finished with value: 0.532656023222061 and parameters: {'learning_rate': 2.3161905836480173e-05, 'batch_size': 16, 'num_train_epochs': 2}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:22,811] Trial 10 finished with value: 0.6302600472813239 and parameters: {'learning_rate': 1.4754227269286479e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:29,711] Trial 11 finished with value: 0.6302600472813239 and parameters: {'learning_rate': 1.5344117892206652e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:37,524] Trial 12 finished with value: 0.6260162601626016 and parameters: {'learning_rate': 1.4732741347431084e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:44,507] Trial 13 finished with value: 0.6079545454545455 and parameters: {'learning_rate': 1.3783000592424313e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:44:52,632] Trial 14 finished with value: 0.6461538461538462 and parameters: {'learning_rate': 1.8361807898357987e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:01,342] Trial 15 finished with value: 0.5068226120857701 and parameters: {'learning_rate': 1.7752080551813286e-05, 'batch_size': 8, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:08,941] Trial 16 finished with value: 0.6057142857142858 and parameters: {'learning_rate': 1.8081031806527168e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:17,119] Trial 17 finished with value: 0.498015873015873 and parameters: {'learning_rate': 4.853030337087592e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:22,908] Trial 18 finished with value: 0.5415282392026578 and parameters: {'learning_rate': 1.2155127707074556e-05, 'batch_size': 8, 'num_train_epochs': 3}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:29,823] Trial 19 finished with value: 0.6079545454545455 and parameters: {'learning_rate': 1.8221050874037653e-05, 'batch_size': 16, 'num_train_epochs': 4}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:37,723] Trial 20 finished with value: 0.518095238095238 and parameters: {'learning_rate': 2.873743748360364e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:44,615] Trial 21 finished with value: 0.5643939393939393 and parameters: {'learning_rate': 1.2612808324626094e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 1 with value: 0.6515151515151515.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:45:51,795] Trial 22 finished with value: 0.6725201708590413 and parameters: {'learning_rate': 1.6438062689835467e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:00,119] Trial 23 finished with value: 0.6080200501253132 and parameters: {'learning_rate': 1.9331092596299587e-05, 'batch_size': 32, 'num_train_epochs': 5}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:07,540] Trial 24 finished with value: 0.6725201708590413 and parameters: {'learning_rate': 1.639547670417738e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:13,637] Trial 25 finished with value: 0.5643939393939393 and parameters: {'learning_rate': 1.23139728092077e-05, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:21,195] Trial 26 finished with value: 0.6515151515151515 and parameters: {'learning_rate': 1.5915805007913156e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:28,448] Trial 27 finished with value: 0.6725201708590413 and parameters: {'learning_rate': 1.6258415265512822e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:36,025] Trial 28 finished with value: 0.5068226120857701 and parameters: {'learning_rate': 1.666144961732363e-05, 'batch_size': 8, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:43,467] Trial 29 finished with value: 0.518095238095238 and parameters: {'learning_rate': 1.1068582133073362e-05, 'batch_size': 16, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:49,464] Trial 30 finished with value: 0.6495238095238096 and parameters: {'learning_rate': 2.0344578681910984e-05, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:46:56,894] Trial 31 finished with value: 0.6079545454545455 and parameters: {'learning_rate': 1.3714819700257155e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:04,008] Trial 32 finished with value: 0.5867612293144208 and parameters: {'learning_rate': 1.050623191718619e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:11,508] Trial 33 finished with value: 0.5851922164214524 and parameters: {'learning_rate': 1.3489193869993204e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:17,757] Trial 34 finished with value: 0.6302600472813239 and parameters: {'learning_rate': 1.653074468808225e-05, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:25,014] Trial 35 finished with value: 0.6541353383458646 and parameters: {'learning_rate': 2.0075738127377606e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:31,917] Trial 36 finished with value: 0.6541353383458646 and parameters: {'learning_rate': 2.0723829181806585e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:38,980] Trial 37 finished with value: 0.6413255360623782 and parameters: {'learning_rate': 2.6885076868271704e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:45,956] Trial 38 finished with value: 0.6541353383458646 and parameters: {'learning_rate': 1.9640937225722925e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:52,366] Trial 39 finished with value: 0.5576923076923077 and parameters: {'learning_rate': 2.1973764247100393e-05, 'batch_size': 8, 'num_train_epochs': 3}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:47:59,269] Trial 40 finished with value: 0.6086956521739131 and parameters: {'learning_rate': 1.7177758012306727e-05, 'batch_size': 16, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:05,992] Trial 41 finished with value: 0.6541353383458646 and parameters: {'learning_rate': 2.0644797112369347e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:13,047] Trial 42 finished with value: 0.6157248157248157 and parameters: {'learning_rate': 2.382697728632434e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:20,150] Trial 43 finished with value: 0.6157248157248157 and parameters: {'learning_rate': 3.193706913712614e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:27,563] Trial 44 finished with value: 0.6515151515151515 and parameters: {'learning_rate': 1.5586171129559877e-05, 'batch_size': 32, 'num_train_epochs': 4}. Best is trial 22 with value: 0.6725201708590413.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:33,701] Trial 45 finished with value: 0.7106918238993711 and parameters: {'learning_rate': 2.1730982555731134e-05, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 45 with value: 0.7106918238993711.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:39,720] Trial 46 finished with value: 0.6461538461538462 and parameters: {'learning_rate': 2.5745063260004655e-05, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 45 with value: 0.7106918238993711.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:44,273] Trial 47 finished with value: 0.4782608695652174 and parameters: {'learning_rate': 1.4396412090485937e-05, 'batch_size': 32, 'num_train_epochs': 2}. Best is trial 45 with value: 0.7106918238993711.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:49,934] Trial 48 finished with value: 0.6057142857142858 and parameters: {'learning_rate': 2.2655006167161002e-05, 'batch_size': 16, 'num_train_epochs': 3}. Best is trial 45 with value: 0.7106918238993711.
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:46: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-5, 5e-5)
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\1610795840.py:69: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2024-12-17 23:48:56,021] Trial 49 finished with value: 0.6302600472813239 and parameters: {'learning_rate': 1.6018091621125056e-05, 'batch_size': 32, 'num_train_epochs': 3}. Best is trial 45 with value: 0.7106918238993711.

Best hyperparameters:
{'learning_rate': 2.1730982555731134e-05, 'batch_size': 32, 'num_train_epochs': 3}

### Fine Tuning on Full Train Set

In [21]:
# Tokenize data
train_tokenized_df = Dataset.from_pandas(train_df).map(preprocess_data, batched=True)
train_tokenized_df = train_tokenized_df.rename_column("sentiment_label", "labels")
train_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

val_tokenized_df = Dataset.from_pandas(val_df).map(preprocess_data, batched=True)
val_tokenized_df = val_tokenized_df.rename_column("sentiment_label", "labels")
val_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Train and evaluate the model using the best hyperparameters from Optuna
best_params = study.best_params

model = AutoModelForSequenceClassification.from_pretrained('ProsusAI/finbert', num_labels=3).to(device)

training_args = TrainingArguments(
    output_dir="./train_results",
    evaluation_strategy="epoch",
    learning_rate=best_params['learning_rate'],
    per_device_train_batch_size=best_params['batch_size'],
    num_train_epochs=best_params['num_train_epochs'],
    weight_decay=0.01,
    save_strategy="epoch",
    logging_dir="./train_logs",
    logging_steps=10,
    disable_tqdm=False,
    load_best_model_at_end=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized_df,
    eval_dataset=val_tokenized_df,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

# Save trained model
output_dir = "./finbert_finetuned_filtered"
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

# Final evaluation on the validation set
model.eval()
all_logits = []

with torch.no_grad():
    for batch in torch.utils.data.DataLoader(val_tokenized_df, batch_size=best_params['batch_size']):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        all_logits.append(logits.cpu())

logits = torch.cat(all_logits, dim=0)
probabilities = torch.softmax(logits, dim=1).cpu().numpy()

# Extract probabilities for each class
prob_negative = probabilities[:, 1]
prob_neutral = probabilities[:, 2]
prob_positive = probabilities[:, 0]

# Transform probabilities into labels
predicted_labels = [
    1 if prob_positive > max(prob_negative, prob_neutral) else 0
    for prob_negative, prob_neutral, prob_positive in zip(prob_negative, prob_neutral, prob_positive)
]

# Add probabilities and predictions to the validation DataFrame
val_df['prob_negative'] = prob_negative
val_df['prob_neutral'] = prob_neutral
val_df['prob_positive'] = prob_positive
val_df['finbert_sentiment_labels'] = predicted_labels

# Final evaluation metrics
if 'sentiment_label' in val_df.columns:
    precision, recall, f1, _ = precision_recall_fscore_support(val_df['sentiment_label'], predicted_labels, average='weighted')
    accuracy = accuracy_score(val_df['sentiment_label'], predicted_labels)

    print(f"Validation Accuracy: {accuracy}")
    print(f"Validation Precision: {precision}")
    print(f"Validation Recall: {recall}")
    print(f"Validation F1-Score: {f1}")

val_df

Map:   0%|          | 0/825 [00:00<?, ? examples/s]

Map:   0%|          | 0/46 [00:00<?, ? examples/s]

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_5748\2610867238.py:29: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation Accuracy: 0.45652173913043476
Validation Precision: 0.4564393939393939
Validation Recall: 0.45652173913043476
Validation F1-Score: 0.4562647754137116

,title,source,topic,company name(s) - cleaned,date,sentiment_label,prob_negative,prob_neutral,prob_positive,finbert_sentiment_labels
31264,Provence Beauty Debuts Exclusively At Ulta Beauty,PR Newswire,Other Specialty Retail,"Ulta Beauty, Inc.",2023-01-04,1,0.560422,0.026716,0.412861,0
1203,American International Group Seeks Inorganic G...,Transcript Collection,Multi-line Insurance,"American International Group, Inc.",2023-02-16,1,0.492326,0.024783,0.482891,0
27522,"Rollins, Inc. Announces New Credit Agreement",PR Newswire,Environmental and Facilities Services,"Rollins, Inc.",2023-02-27,0,0.594066,0.025744,0.380190,0
28241,"Super Micro Computer, Inc. - Special Call",Company Website,"Technology Hardware, Storage and Peripherals","Super Micro Computer, Inc.",2023-03-09,0,0.460125,0.041321,0.498554,1
15390,Hershey's KISSES Announces to Introduce New He...,PR Newswire,Packaged Foods and Meats,The Hershey Company,2023-03-15,1,0.503770,0.024260,0.471970,0
12413,Fair Isaac Corporation - Special Call,Business Wire,Application Software,Fair Isaac Corporation,2023-03-30,0,0.415581,0.037775,0.546644,1
2463,Aon More Actively Considering M&A Opportunities,Other,Insurance Brokers,Aon plc,2023-03-31,1,0.501279,0.029584,0.469137,0
10030,DTE Energy Company - Special Call,Company Website,Multi-Utilities,DTE Energy Company,2023-04-03,1,0.433389,0.036526,0.530085,1
23878,Northern Trust to Provide Asset Servicing Solu...,Business Wire,Asset Management and Custody Banks,Northern Trust Corporation,2023-04-11,1,0.315626,0.017073,0.667300,1
17262,Georgia United Credit Union Strengthens Digita...,PR Newswire,Transaction and Payment Processing Services,"Jack Henry & Associates, Inc.",2023-04-12,0,0.502797,0.026640,0.470563,0
22302,HashiCorp and Microsoft Collaborate to Help Or...,GlobeNewswire,"HashiCorp, Inc. (NasdaqGS:HCP) (Application So...","HashiCorp, Inc.",2023-04-25,1,0.544993,0.022531,0.432475,0
10953,"Enphase Energy, Inc. Presents at Smart Energy ...",GlobeNewswire,Semiconductor Materials and Equipment,"Enphase Energy, Inc.",2023-05-03,1,0.503556,0.027125,0.469318,0
23077,"NextEra Energy Partners, LP, NextEra Energy, I...",PR Newswire; Company Website,"NextEra Energy Partners, LP (NYSE:NEP) (Renewa...","NextEra Energy Partners, LP",2023-05-08,1,0.422262,0.038586,0.539153,1
10549,Equifax Helps Employers Combat Unemployment Fr...,PR Newswire,Research and Consulting Services,Equifax Inc.,2023-05-16,1,0.536191,0.019061,0.444747,0
4217,Booking Holdings Inc. Enters into Credit Agree...,SEC Form 8k,"Hotels, Resorts and Cruise Lines",Booking Holdings Inc.,2023-05-19,0,0.609328,0.026251,0.364421,0
29915,Teleflex Incorporated Wins Agreements with Pre...,GlobeNewswire,Health Care Equipment,Teleflex Incorporated,2023-06-01,1,0.432999,0.026977,0.540024,1
6241,Constellation Energy Corporation - Special Call,Company Website,Electric Utilities,Constellation Energy Corporation,2023-06-01,1,0.428200,0.040267,0.531533,1
31283,"Ulta Beauty, Inc. Approves Amendments Bylaws",SEC Form 8k,Other Specialty Retail,"Ulta Beauty, Inc.",2023-06-07,1,0.534033,0.026252,0.439716,0
15529,Oklahoma Health Care Authority Announces Inten...,Business Wire,Managed Health Care,Humana Inc.,2023-06-08,0,0.440033,0.019011,0.540957,1
17721,Chase Launches Chase Freedom Rise,Business Wire,Diversified Banks,JPMorgan Chase & Co.,2023-06-12,0,0.458931,0.044450,0.496618,1
17494,"Juniper Networks, Inc. Enters into Credit Agre...",SEC Form 8k,Communications Equipment,"Juniper Networks, Inc.",2023-06-15,0,0.620190,0.025514,0.354296,0
12643,Fox Corporation Enters into a Credit Agreement,SEC Form 8k,Broadcasting,Fox Corporation,2023-06-15,0,0.714424,0.020869,0.264707,0
28261,"Super Micro Computer, Inc. - Special Call",Company Website,"Technology Hardware, Storage and Peripherals","Super Micro Computer, Inc.",2023-06-20,0,0.460125,0.041321,0.498554,1
12423,Fair Isaac Corporation - Special Call,Business Wire,Application Software,Fair Isaac Corporation,2023-06-20,0,0.415581,0.037775,0.546644,1
24729,Community Health Systems Tap Oracle to Help Im...,PR Newswire,Systems Software,Oracle Corporation,2023-06-27,0,0.586341,0.021178,0.392481,0
32967,Wells Fargo & Company Approves and Adopts the ...,SEC Form 8k,Diversified Banks,Wells Fargo & Company,2023-06-29,1,0.525949,0.023253,0.450799,0
23894,Northern Trust Asset Management Announces Mana...,Other,Asset Management and Custody Banks,Northern Trust Corporation,2023-07-14,0,0.482209,0.024147,0.493644,1
6778,Comcast’s MachineQ Extends its Indoor Asset Tr...,Business Wire,Cable and Satellite,Comcast Corporation,2023-07-20,1,0.547740,0.022787,0.429474,0
13708,Milberg Lawsuit Accuses Google of Misleading T...,PR Newswire,Interactive Media and Services,Alphabet Inc.,2023-07-31,0,0.700295,0.021476,0.278229,0
31468,UPS Teamsters Local Unions Endorse Tentative A...,PR Newswire,Air Freight and Logistics,"United Parcel Service, Inc.",2023-07-31,0,0.469886,0.022600,0.507514,1
18960,Leidos Wins $918 Million Department of Homelan...,PR Newswire,Research and Consulting Services,"Leidos Holdings, Inc.",2023-09-07,0,0.483383,0.021412,0.495205,1
31823,Valero Energy Corporation - Special Call,Company Website,Oil and Gas Refining and Marketing,Valero Energy Corporation,2023-09-21,1,0.387956,0.037112,0.574933,1
2315,Our Place Expands Reach Through Amazon Launch,PR Newswire,"Amazon.com, Inc. (NasdaqGS:AMZN) (Broadline Re...","Amazon.com, Inc.",2023-10-04,1,0.358631,0.020272,0.621097,1
1854,"Advanced Micro Devices, Inc. - Special Call",Company Website,Semiconductors,"Advanced Micro Devices, Inc.",2023-10-10,1,0.402119,0.036538,0.561344,1
1855,"Advanced Micro Devices, Inc. - Special Call",Company Website,Semiconductors,"Advanced Micro Devices, Inc.",2023-10-11,0,0.402119,0.036538,0.561344,1
1859,"Advanced Micro Devices, Inc. - Special Call",Company Website,Semiconductors,"Advanced Micro Devices, Inc.",2023-10-17,0,0.402119,0.036538,0.561344,1
29996,Target Corporation Enters into 364-Day Credit ...,SEC Form 8k,Consumer Staples Merchandise Retail,Target Corporation,2023-10-18,1,0.659725,0.026358,0.313918,0
20080,"Live Nation Entertainment, Inc. - Special Call",Company Website,Movies and Entertainment,"Live Nation Entertainment, Inc.",2023-11-09,0,0.368679,0.037426,0.593895,1
2377,Arista Networks Unveils Zero Trust Networking ...,Business Wire,Communications Equipment,Arista Networks Inc,2023-11-09,0,0.440398,0.026734,0.532868,1
11442,Eaton Wins Contract to Help Miami-Dade County ...,Business Wire,Electrical Components and Equipment,Eaton Corporation plc,2023-11-28,0,0.502972,0.018474,0.478554,0
9265,Dell Technologies Inc. Announces Cash Tender O...,SEC Form 8k,"Technology Hardware, Storage and Peripherals",Dell Technologies Inc.,2023-12-04,0,0.501110,0.025696,0.473194,0
8203,Cisco Redefines Cybersecurity Defense with Pow...,PR Newswire,Communications Equipment,"Cisco Systems, Inc.",2023-12-05,1,0.432808,0.020553,0.546639,1
1878,"Advanced Micro Devices, Inc. - Special Call",GlobeNewswire; Company Website,Semiconductors,"Advanced Micro Devices, Inc.",2023-12-06,1,0.402119,0.036538,0.561344,1
10061,DTE Energy Company - Special Call,GlobeNewswire; Company Website,Multi-Utilities,DTE Energy Company,2023-12-08,1,0.433388,0.036526,0.530085,1
31742,Visa Provisioning Intelligence Launches to Com...,Business Wire,Transaction and Payment Processing Services,Visa Inc.,2023-12-13,0,0.505320,0.025902,0.468777,0
2347,Amazon and Readyland Revolutionize Interactive...,PR Newswire,Broadline Retail,"Amazon.com, Inc.",2023-12-14,1,0.537356,0.027500,0.435144,0

### Fitting on Test Set

In [23]:
# Load the saved model and tokenizer
output_dir = "./finbert_finetuned_filtered"
model = AutoModelForSequenceClassification.from_pretrained(output_dir).to(device)
tokenizer = AutoTokenizer.from_pretrained(output_dir)
model.eval()

# Tokenize the test set using the saved tokenizer
test_tokenized_df = Dataset.from_pandas(test_df).map(preprocess_data, batched=True)
test_tokenized_df = test_tokenized_df.rename_column("sentiment_label", "labels")
test_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Run predictions on the test set
all_logits = []
with torch.no_grad():
    for batch in torch.utils.data.DataLoader(test_tokenized_df, batch_size=best_params['batch_size']):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        all_logits.append(logits.cpu())

logits = torch.cat(all_logits, dim=0)
probabilities = torch.softmax(logits, dim=1).cpu().numpy()

prob_negative = probabilities[:, 1]
prob_neutral = probabilities[:, 2]
prob_positive = probabilities[:, 0]

predicted_labels = [
    1 if prob_positive > max(prob_negative, prob_neutral) else 0
    for prob_negative, prob_neutral, prob_positive in zip(prob_negative, prob_neutral, prob_positive)
]

# Save predictions to test DataFrame
test_df_results = test_df.copy()
test_df_results['prob_negative'] = prob_negative
test_df_results['prob_neutral'] = prob_neutral
test_df_results['prob_positive'] = prob_positive
test_df_results['finbert_sentiment_labels'] = predicted_labels

# Evaluate metrics if ground-truth labels exist
if 'sentiment_label' in test_df_results.columns:
    precision, recall, f1, _ = precision_recall_fscore_support(
        test_df_results['sentiment_label'], predicted_labels, average='weighted'
    )
    accuracy = accuracy_score(test_df_results['sentiment_label'], predicted_labels)

    print(f"Test Accuracy: {accuracy}")
    print(f"Test Precision: {precision}")
    print(f"Test Recall: {recall}")
    print(f"Test F1-Score: {f1}")

test_df_results

Map:   0%|          | 0/390 [00:00<?, ? examples/s]

Test Accuracy: 0.5974358974358974
Test Precision: 0.6081089743589744
Test Recall: 0.5974358974358974
Test F1-Score: 0.6019302335091807

,title,source,topic,company name(s) - cleaned,date,sentiment_label,prob_negative,prob_neutral,prob_positive,finbert_sentiment_labels
58421,Visa Reimagines Customer Loyalty with New Web3...,Business Wire,Transaction and Payment Processing Services,Visa Inc.,2024-01-04,1,0.423700,0.021572,0.554728,1
43862,True Potential Appoints Northern Trust for Ass...,Business Wire,Asset Management and Custody Banks,Northern Trust Corporation,2024-01-19,0,0.455273,0.023059,0.521668,1
60612,Wells Fargo & Company Approves and Adopts the ...,SEC Form 8k,Diversified Banks,Wells Fargo & Company,2024-01-24,1,0.507237,0.024754,0.468009,0
642,Abbott Laboratories Enters into Five Year Cred...,SEC Form 8k,Health Care Equipment,Abbott Laboratories,2024-01-29,1,0.788146,0.014926,0.196928,0
35225,Leidos Wins Contract to Support Advanced Resea...,PR Newswire,Research and Consulting Services,"Leidos Holdings, Inc.",2024-01-29,0,0.437296,0.020836,0.541868,1
...,...,...,...,...,...,...,...,...,...,...
31428,What s More Wicked than the Crime of,https://mises.org/podcasts/human-action-podcas...,economics,NaN,2024-12-13,0,0.648875,0.140803,0.210322,0
3589,Nice for them nice for your wallet,https://www.komando.com/tips/nice-for-them-nic...,tech,NaN,2024-12-13,0,0.533973,0.044016,0.422011,0
35218,The Missing Secret,https://mises.org/friday-philosophy/missing-se...,economics,NaN,2024-12-13,0,0.664648,0.110303,0.225049,0
21538,What s More Wicked than the Crime of,https://mises.org/podcasts/human-action-podcas...,economics,NaN,2024-12-13,0,0.648875,0.140803,0.210322,0
21356,The Missing Secret,https://mises.org/friday-philosophy/missing-se...,economics,NaN,2024-12-13,0,0.664648,0.110303,0.225049,0

In [24]:
# Save predictions to the test dataframe
test_df_results.to_csv("results/test_df_results_filtered.csv", index=False)