In [44]:
# Run this if facing issue with transformers
# pip install torch torchvision torchaudio transformers

import pandas as pd
import numpy as np
import torch
import re
import random
from transformers import BertForSequenceClassification, BertTokenizer, AutoTokenizer, AutoModelForSequenceClassification, pipeline, Trainer, TrainingArguments
from datasets import Dataset
from scipy.stats import loguniform
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
#import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score, roc_curve
# from sklearn.model_selection import ParameterGrid
# import tiktoken

In [2]:
train_df = pd.read_csv('Data Updated/train_df.csv')
val_df = pd.read_csv('Data Updated/val_df.csv')
test_df = pd.read_csv('Data Updated/test_df.csv')

In [3]:
# Apply preprocessing to datasets
def clean_text(text):
    if isinstance(text, str):
        # Convert to lowercase
        text = text.lower()
        # Remove special characters and punctuation
        text = re.sub(r"[^\w\s]", "", text)
        # Remove extra spaces
        text = re.sub(r"\s+", " ", text).strip()
    else:
        text = ""
    return text

def preprocess_dataset(df):
    df['title'] = df['title'].apply(clean_text)
    df['sentiment_label'] = df['sentiment_label'].astype(int)
    df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # Shuffle dataset
    return df

train_df = preprocess_dataset(train_df)
val_df = preprocess_dataset(val_df)
test_df = preprocess_dataset(test_df)

In [4]:
# # REMOVE LATER - for testing labelling only
# train_df = train_df.head(600)
# val_df = val_df.head(200)
# test_df = test_df.head(200)

# Prepare df for labelling results
test_df_results = test_df.copy()

In [5]:
# Check distribution of labels
print(train_df['sentiment_label'].value_counts())
print(val_df['sentiment_label'].value_counts())
print(test_df['sentiment_label'].value_counts())

sentiment_label
1    133131
0    128476
Name: count, dtype: int64
sentiment_label
1    32626
0    31459
Name: count, dtype: int64
sentiment_label
0    14673
1    13714
Name: count, dtype: int64

# FinBERT (Fine Tuned for Sentiment Analysis)
FinBERT is a pre-trained text analysis model, trained on financial data. It labels financial data as either "positive", "neutral" or "negative" by assigning a probability to each class, and return the class with the highest probability.
<br> For our use case, we labelled sentiments using only '1' or '0' for the excess 3 day aggregated returns. Hence, we will first fine tune finBERT to label using 2 classifications on our training set, then using random search to search for the best parameters that will return the model with the highest F1 by evaluating its performance on the valuation set.

## Hyperparameter Optimisation using Random Search (Key Evaluation Metric: f1)

In [8]:
# Select subset of train data for hyperparameter optimization
train_subset_df = train_df.sample(frac=0.1, random_state=42)

# If gpu available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load tokenizer and model
tokenizer = BertTokenizer.from_pretrained("ProsusAI/finbert")
model = BertForSequenceClassification.from_pretrained('ProsusAI/finbert', num_labels=2, ignore_mismatched_sizes=True).to(device)
model.config.problem_type = "single_label_classification" # To use finBERT for 2 labels

# Tokenize data
def preprocess_data(example):
    tokenized = tokenizer(example['title'], padding='max_length', max_length=128, truncation=True)
    tokenized['labels'] = example['sentiment_label']
    return tokenized

train_subset_tokenized_df = Dataset.from_pandas(train_subset_df).map(preprocess_data, batched=True)
train_subset_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

train_tokenized_df = Dataset.from_pandas(train_df).map(preprocess_data, batched=True)
train_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

val_tokenized_df = Dataset.from_pandas(val_df).map(preprocess_data, batched=True)
val_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

test_tokenized_df = Dataset.from_pandas(test_df).map(preprocess_data, batched=True)
test_tokenized_df.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Define random parameter space
random_param_space = {
    "learning_rate": loguniform(1e-6, 5e-5).rvs(50).tolist(),
    "batch_size": [16, 32],
    "num_epochs": [2, 3, 4],
    "threshold": np.random.uniform(0.1, 0.7, 50).tolist(),
    "weight_decay": [0.0, 0.01, 0.1]
}

num_random_samples = 50
random_param_combinations = [
    {
        "learning_rate": random.choice(random_param_space["learning_rate"]),
        "batch_size": random.choice(random_param_space["batch_size"]),
        "num_epochs": random.choice(random_param_space["num_epochs"]),
        "threshold": random.choice(random_param_space["threshold"]),
        "weight_decay": random.choice(random_param_space["weight_decay"]),
    }
    for _ in range(num_random_samples)
]

best_f1 = 0
best_params = None
best_threshold = None
best_model = None

# Define metrics
def compute_metrics(eval_pred):
    predictions, labels = eval_pred.predictions, eval_pred.label_ids
    predicted_probabilities = torch.softmax(torch.tensor(predictions), dim=1).numpy()

    # Apply threshold from params
    threshold = params["threshold"]
    predicted_labels = (predicted_probabilities[:, 1] >= threshold).astype(int)

    # Calculate metrics
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predicted_labels, average='binary')
    accuracy = accuracy_score(labels, predicted_labels)

    return {
        'eval_accuracy': accuracy,
        'eval_precision': precision,
        'eval_recall': recall,
        'eval_f1': f1
    }

# Perform random search
for params in random_param_combinations:
    print(f"Training with parameters: {params}")

    # Define training arguments
    training_args = TrainingArguments(
        output_dir='./train_subset_results',
        evaluation_strategy='epoch',  # Evaluates at the end of each epoch
        save_strategy='epoch',  # Saves the model at the end of each epoch
        logging_dir='./train_subset_logs',
        logging_steps=10,  # Log training loss every 10 steps
        logging_first_step=True,  # Log the first step to capture initial metrics
        per_device_train_batch_size=params['batch_size'],
        learning_rate=params['learning_rate'],
        num_train_epochs=params['num_epochs'],
        weight_decay=params['weight_decay'],
        load_best_model_at_end=True,
        metric_for_best_model='eval_f1',
        save_total_limit=1
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_subset_tokenized_df,
        eval_dataset=val_tokenized_df,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics
    )

    # Train and evaluate
    trainer.train()
    eval_metrics = trainer.evaluate()
    print("Validation metrics:", eval_metrics)

    # Track best model
    if 'eval_f1' in eval_metrics and eval_metrics['eval_f1'] > best_f1:
        best_f1 = eval_metrics['eval_f1']
        best_metrics = eval_metrics
        best_params = params
        best_threshold = params['threshold']
        best_model = trainer.model
        trainer.save_model("./finbert_train_subset_model")
        tokenizer.save_pretrained("./finbert_train_subset_model")

print("Best F1 Score:", best_f1)
print("Best Eval Metrics:", best_metrics)
print("Best Parameters:", best_params)
print("Best Threshold:", best_threshold)

Using device: cuda

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at ProsusAI/finbert and are newly initialized because the shapes did not match:
- classifier.weight: found shape torch.Size([3, 768]) in the checkpoint and torch.Size([2, 768]) in the model instantiated
- classifier.bias: found shape torch.Size([3]) in the checkpoint and torch.Size([2]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/26161 [00:00<?, ? examples/s]

Map:   0%|          | 0/261607 [00:00<?, ? examples/s]

Map:   0%|          | 0/64085 [00:00<?, ? examples/s]

Map:   0%|          | 0/28387 [00:00<?, ? examples/s]

Training with parameters: {'learning_rate': 1.6119044727609192e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.3565246110151298, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5091050947959741, 'eval_precision': 0.5091050947959741, 'eval_recall': 1.0, 'eval_f1': 0.6747112531149507, 'eval_loss': 0.6935189366340637, 'eval_runtime': 64.4988, 'eval_samples_per_second': 993.585, 'eval_steps_per_second': 124.204, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.049268011541736e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.3565246110151298, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5091050947959741, 'eval_precision': 0.5091053789616591, 'eval_recall': 0.9999693495984797, 'eval_f1': 0.674704525948981, 'eval_loss': 0.6948598027229309, 'eval_runtime': 64.2777, 'eval_samples_per_second': 997.002, 'eval_steps_per_second': 124.631, 'epoch': 2.0}
Training with parameters: {'learning_rate': 3.5067764992972196e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.14442679104045422, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5091519076226886, 'eval_precision': 0.5091289285602821, 'eval_recall': 1.0, 'eval_f1': 0.6747321834801671, 'eval_loss': 0.7248985171318054, 'eval_runtime': 64.9805, 'eval_samples_per_second': 986.219, 'eval_steps_per_second': 123.283, 'epoch': 4.0}
Training with parameters: {'learning_rate': 4.12320653261873e-05, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.26856070581242847, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5100101427791215, 'eval_precision': 0.5104767117664164, 'eval_recall': 0.9147305829706369, 'eval_f1': 0.6552712182590653, 'eval_loss': 0.7468686699867249, 'eval_runtime': 64.9257, 'eval_samples_per_second': 987.051, 'eval_steps_per_second': 123.387, 'epoch': 2.0}
Training with parameters: {'learning_rate': 1.4537555576161948e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.5972425054911575, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5046110634313802, 'eval_precision': 0.5149923247484223, 'eval_recall': 0.46272911175136394, 'eval_f1': 0.48746387691512894, 'eval_loss': 1.2284764051437378, 'eval_runtime': 63.9491, 'eval_samples_per_second': 1002.125, 'eval_steps_per_second': 125.271, 'epoch': 4.0}
Training with parameters: {'learning_rate': 6.938901412739403e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.31507943712656356, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.511383319029414, 'eval_precision': 0.5141532823110919, 'eval_recall': 0.7309814258566787, 'eval_f1': 0.603688094062852, 'eval_loss': 1.1689237356185913, 'eval_runtime': 64.2041, 'eval_samples_per_second': 998.144, 'eval_steps_per_second': 124.774, 'epoch': 2.0}
Training with parameters: {'learning_rate': 7.790143126276244e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.5625803079727366, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5059218225793868, 'eval_precision': 0.5140727750986409, 'eval_recall': 0.5391099123398516, 'eval_f1': 0.526293741865023, 'eval_loss': 2.450373411178589, 'eval_runtime': 64.1719, 'eval_samples_per_second': 998.646, 'eval_steps_per_second': 124.837, 'epoch': 2.0}
Training with parameters: {'learning_rate': 1.7258215396625017e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.3140519960161536, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5090738862448311, 'eval_precision': 0.5138614568212645, 'eval_recall': 0.6618647704284926, 'eval_f1': 0.5785476027810151, 'eval_loss': 1.7007235288619995, 'eval_runtime': 63.7104, 'eval_samples_per_second': 1005.88, 'eval_steps_per_second': 125.741, 'epoch': 2.0}
Training with parameters: {'learning_rate': 1.255111517297383e-06, 'batch_size': 16, 'num_epochs': 3, 'threshold': 0.1530955012311517, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5076070843411095, 'eval_precision': 0.5134449772778629, 'eval_recall': 0.6268007110893152, 'eval_f1': 0.5644883030846732, 'eval_loss': 2.3604676723480225, 'eval_runtime': 63.7594, 'eval_samples_per_second': 1005.107, 'eval_steps_per_second': 125.644, 'epoch': 3.0}
Training with parameters: {'learning_rate': 3.1357757322577464e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.4136396976291964, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5057345712725286, 'eval_precision': 0.5125577710286544, 'eval_recall': 0.5948629927052045, 'eval_f1': 0.5506518562653389, 'eval_loss': 1.9879919290542603, 'eval_runtime': 63.6845, 'eval_samples_per_second': 1006.289, 'eval_steps_per_second': 125.792, 'epoch': 2.0}
Training with parameters: {'learning_rate': 4.3709904681305046e-05, 'batch_size': 16, 'num_epochs': 3, 'threshold': 0.6531245410138701, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5022236092689397, 'eval_precision': 0.5119211822660098, 'eval_recall': 0.47777845889781156, 'eval_f1': 0.49426089162280423, 'eval_loss': 1.4471148252487183, 'eval_runtime': 64.1645, 'eval_samples_per_second': 998.761, 'eval_steps_per_second': 124.851, 'epoch': 3.0}
Training with parameters: {'learning_rate': 5.418282319533245e-06, 'batch_size': 32, 'num_epochs': 4, 'threshold': 0.5972425054911575, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5026917375360849, 'eval_precision': 0.5125623130608176, 'eval_recall': 0.4727211426469687, 'eval_f1': 0.49183621404426303, 'eval_loss': 1.470720648765564, 'eval_runtime': 63.9535, 'eval_samples_per_second': 1002.057, 'eval_steps_per_second': 125.263, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.8410729205738687e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.26856070581242847, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5072481860029648, 'eval_precision': 0.5132229736549914, 'eval_recall': 0.6233678661190462, 'eval_f1': 0.5629584521272178, 'eval_loss': 1.6168606281280518, 'eval_runtime': 64.0333, 'eval_samples_per_second': 1000.807, 'eval_steps_per_second': 125.107, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.8408992080552519e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.5241144063085703, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5037372239993758, 'eval_precision': 0.5133956183469514, 'eval_recall': 0.48338748237601914, 'eval_f1': 0.4979398531849396, 'eval_loss': 2.9487686157226562, 'eval_runtime': 63.9613, 'eval_samples_per_second': 1001.933, 'eval_steps_per_second': 125.248, 'epoch': 2.0}
Training with parameters: {'learning_rate': 1.1992724522955155e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.5892768570729005, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5035031598658032, 'eval_precision': 0.5130179802796933, 'eval_recall': 0.4879850426040581, 'eval_f1': 0.5001885014137606, 'eval_loss': 2.391542434692383, 'eval_runtime': 64.4244, 'eval_samples_per_second': 994.732, 'eval_steps_per_second': 124.347, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.2948683681130555e-06, 'batch_size': 32, 'num_epochs': 4, 'threshold': 0.4367663185416978, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.50429897791995, 'eval_precision': 0.5124829249861946, 'eval_recall': 0.540458530006743, 'eval_f1': 0.5260990855250399, 'eval_loss': 1.4274002313613892, 'eval_runtime': 63.9086, 'eval_samples_per_second': 1002.76, 'eval_steps_per_second': 125.351, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.8410729205738687e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.4136396976291964, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5033939299368027, 'eval_precision': 0.5118959218225562, 'eval_recall': 0.5282290198001593, 'eval_f1': 0.5199342313668109, 'eval_loss': 2.008216619491577, 'eval_runtime': 64.1612, 'eval_samples_per_second': 998.812, 'eval_steps_per_second': 124.857, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.083858126934475e-06, 'batch_size': 32, 'num_epochs': 3, 'threshold': 0.5813181884524238, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5029258016696575, 'eval_precision': 0.5122712080216457, 'eval_recall': 0.4932569116655428, 'eval_f1': 0.5025842819443794, 'eval_loss': 3.2298989295959473, 'eval_runtime': 64.0122, 'eval_samples_per_second': 1001.137, 'eval_steps_per_second': 125.148, 'epoch': 3.0}
Training with parameters: {'learning_rate': 2.752069685079053e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.5633468615779944, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5038620582039479, 'eval_precision': 0.5130034738522204, 'eval_recall': 0.5024213817201005, 'eval_f1': 0.5076572879728705, 'eval_loss': 4.941563129425049, 'eval_runtime': 64.15, 'eval_samples_per_second': 998.986, 'eval_steps_per_second': 124.879, 'epoch': 4.0}
Training with parameters: {'learning_rate': 2.03664420268309e-06, 'batch_size': 16, 'num_epochs': 3, 'threshold': 0.5374043008245923, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5026449247093704, 'eval_precision': 0.511875847711573, 'eval_recall': 0.4973947158707779, 'eval_f1': 0.5045313933062848, 'eval_loss': 3.646695137023926, 'eval_runtime': 64.0423, 'eval_samples_per_second': 1000.667, 'eval_steps_per_second': 125.089, 'epoch': 3.0}
Training with parameters: {'learning_rate': 1.8410729205738687e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.3962773578186345, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5028477802918, 'eval_precision': 0.511237603427029, 'eval_recall': 0.5340525960890088, 'eval_f1': 0.5223961144090664, 'eval_loss': 2.7995359897613525, 'eval_runtime': 63.8689, 'eval_samples_per_second': 1003.384, 'eval_steps_per_second': 125.429, 'epoch': 4.0}
Training with parameters: {'learning_rate': 2.2948683681130555e-06, 'batch_size': 32, 'num_epochs': 3, 'threshold': 0.527946872333797, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.502941405945229, 'eval_precision': 0.5121897303101118, 'eval_recall': 0.49711886225709556, 'eval_f1': 0.5045417781372488, 'eval_loss': 4.531703948974609, 'eval_runtime': 63.9756, 'eval_samples_per_second': 1001.71, 'eval_steps_per_second': 125.22, 'epoch': 3.0}
Training with parameters: {'learning_rate': 1.5958573588141284e-05, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.4256176498949491, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5007412030896465, 'eval_precision': 0.5093153030795122, 'eval_recall': 0.5287194262244835, 'eval_f1': 0.5188360027069705, 'eval_loss': 1.55515718460083, 'eval_runtime': 64.1529, 'eval_samples_per_second': 998.942, 'eval_steps_per_second': 124.874, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.3628864184236417e-05, 'batch_size': 32, 'num_epochs': 4, 'threshold': 0.48253448281312783, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5037216197238044, 'eval_precision': 0.5126275039941011, 'eval_recall': 0.5114019493655367, 'eval_f1': 0.5120139933102157, 'eval_loss': 1.6885440349578857, 'eval_runtime': 65.9654, 'eval_samples_per_second': 971.494, 'eval_steps_per_second': 121.442, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.465352103067214e-06, 'batch_size': 32, 'num_epochs': 3, 'threshold': 0.26856070581242847, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5051416088008114, 'eval_precision': 0.5135762081784386, 'eval_recall': 0.5293017838533685, 'eval_f1': 0.521320432899126, 'eval_loss': 3.9994583129882812, 'eval_runtime': 64.0233, 'eval_samples_per_second': 1000.964, 'eval_steps_per_second': 125.126, 'epoch': 3.0}
Training with parameters: {'learning_rate': 1.2897950480855547e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.11525147604645712, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.504049309510806, 'eval_precision': 0.5126549974479839, 'eval_recall': 0.5233556059584381, 'eval_f1': 0.5179500401923165, 'eval_loss': 4.550652980804443, 'eval_runtime': 65.158, 'eval_samples_per_second': 983.533, 'eval_steps_per_second': 122.947, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.9621516588303503e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.3332063738136892, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5039868924085199, 'eval_precision': 0.5119233720831083, 'eval_recall': 0.5520443817814014, 'eval_f1': 0.531227418189326, 'eval_loss': 1.7842810153961182, 'eval_runtime': 63.8859, 'eval_samples_per_second': 1003.116, 'eval_steps_per_second': 125.395, 'epoch': 4.0}
Training with parameters: {'learning_rate': 7.475992999956507e-06, 'batch_size': 16, 'num_epochs': 3, 'threshold': 0.5241144063085703, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5045330420535227, 'eval_precision': 0.5124757336987553, 'eval_recall': 0.5502053576901857, 'eval_f1': 0.5306707659561889, 'eval_loss': 4.150017738342285, 'eval_runtime': 63.6516, 'eval_samples_per_second': 1006.809, 'eval_steps_per_second': 125.857, 'epoch': 3.0}
Training with parameters: {'learning_rate': 1.1992724522955155e-06, 'batch_size': 32, 'num_epochs': 4, 'threshold': 0.6817507766587351, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5040337052352345, 'eval_precision': 0.513461661444011, 'eval_recall': 0.4921841476123337, 'eval_f1': 0.5025978090766823, 'eval_loss': 3.6886794567108154, 'eval_runtime': 63.9379, 'eval_samples_per_second': 1002.301, 'eval_steps_per_second': 125.293, 'epoch': 4.0}
Training with parameters: {'learning_rate': 3.385226783451977e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.28658939302939734, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5025981118826558, 'eval_precision': 0.511132882080513, 'eval_recall': 0.527707962974315, 'eval_f1': 0.5192881918262705, 'eval_loss': 4.322473526000977, 'eval_runtime': 63.8098, 'eval_samples_per_second': 1004.313, 'eval_steps_per_second': 125.545, 'epoch': 4.0}
Training with parameters: {'learning_rate': 2.0609249413202354e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.1447303862078625, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.503035031598658, 'eval_precision': 0.5114749262536873, 'eval_recall': 0.5314473119597867, 'eval_f1': 0.5212698794456303, 'eval_loss': 4.1146345138549805, 'eval_runtime': 63.9153, 'eval_samples_per_second': 1002.655, 'eval_steps_per_second': 125.338, 'epoch': 2.0}
Training with parameters: {'learning_rate': 1.083858126934475e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.4136396976291964, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5026449247093704, 'eval_precision': 0.5115792711056435, 'eval_recall': 0.5098387788880034, 'eval_f1': 0.5107075421009809, 'eval_loss': 4.726242542266846, 'eval_runtime': 63.1705, 'eval_samples_per_second': 1014.477, 'eval_steps_per_second': 126.816, 'epoch': 2.0}
Training with parameters: {'learning_rate': 3.28774741399112e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.1530955012311517, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5038776624795194, 'eval_precision': 0.5114860014357502, 'eval_recall': 0.567798688162815, 'eval_f1': 0.5381732612863867, 'eval_loss': 5.254234313964844, 'eval_runtime': 63.8738, 'eval_samples_per_second': 1003.307, 'eval_steps_per_second': 125.419, 'epoch': 4.0}
Training with parameters: {'learning_rate': 3.124565071260875e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.5892768570729005, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5030194273230866, 'eval_precision': 0.5122574538570752, 'eval_recall': 0.49763991908294, 'eval_f1': 0.5048428973430139, 'eval_loss': 6.119822978973389, 'eval_runtime': 64.0566, 'eval_samples_per_second': 1000.444, 'eval_steps_per_second': 125.061, 'epoch': 2.0}
Training with parameters: {'learning_rate': 4.3709904681305046e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.5633468615779944, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5045642506046657, 'eval_precision': 0.5136969166301832, 'eval_recall': 0.5034941457733096, 'eval_f1': 0.5085443625781685, 'eval_loss': 2.195143222808838, 'eval_runtime': 63.5581, 'eval_samples_per_second': 1008.29, 'eval_steps_per_second': 126.042, 'epoch': 4.0}
Training with parameters: {'learning_rate': 4.12320653261873e-05, 'batch_size': 16, 'num_epochs': 3, 'threshold': 0.6921321619603104, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5034251384879457, 'eval_precision': 0.5131574635425201, 'eval_recall': 0.47995463740575, 'eval_f1': 0.4960010136044725, 'eval_loss': 2.79286789894104, 'eval_runtime': 63.663, 'eval_samples_per_second': 1006.628, 'eval_steps_per_second': 125.834, 'epoch': 3.0}
Training with parameters: {'learning_rate': 1.0401663679887314e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.6531245410138701, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5025512990559413, 'eval_precision': 0.5111943653529147, 'eval_recall': 0.5227732483295531, 'eval_f1': 0.5169189737994575, 'eval_loss': 4.037820816040039, 'eval_runtime': 64.1761, 'eval_samples_per_second': 998.58, 'eval_steps_per_second': 124.828, 'epoch': 4.0}
Training with parameters: {'learning_rate': 3.385226783451977e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.11525147604645712, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.504236560817664, 'eval_precision': 0.5117778328787503, 'eval_recall': 0.5693618586403482, 'eval_f1': 0.5390363158887455, 'eval_loss': 2.6641125679016113, 'eval_runtime': 63.848, 'eval_samples_per_second': 1003.713, 'eval_steps_per_second': 125.47, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.0609249413202354e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.5564710291701385, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5038308496528049, 'eval_precision': 0.5131191644247508, 'eval_recall': 0.49690430944645375, 'eval_f1': 0.5048815807913299, 'eval_loss': 5.058962821960449, 'eval_runtime': 63.8155, 'eval_samples_per_second': 1004.223, 'eval_steps_per_second': 125.534, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.3628864184236417e-05, 'batch_size': 16, 'num_epochs': 3, 'threshold': 0.13813501017161417, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5082936724662558, 'eval_precision': 0.5169324221716022, 'eval_recall': 0.5216698338748238, 'eval_f1': 0.5192903235648579, 'eval_loss': 3.842524290084839, 'eval_runtime': 63.8194, 'eval_samples_per_second': 1004.162, 'eval_steps_per_second': 125.526, 'epoch': 3.0}
Training with parameters: {'learning_rate': 7.475992999956507e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.11525147604645712, 'weight_decay': 0.1}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5035655769680892, 'eval_precision': 0.5116935483870968, 'eval_recall': 0.5445350334089376, 'eval_f1': 0.5276037181124343, 'eval_loss': 2.5778026580810547, 'eval_runtime': 64.5245, 'eval_samples_per_second': 993.188, 'eval_steps_per_second': 124.154, 'epoch': 4.0}
Training with parameters: {'learning_rate': 2.752069685079053e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.6921321619603104, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5028945931185145, 'eval_precision': 0.5114492451537981, 'eval_recall': 0.5264512965119843, 'eval_f1': 0.518841849295413, 'eval_loss': 4.956788063049316, 'eval_runtime': 64.0067, 'eval_samples_per_second': 1001.224, 'eval_steps_per_second': 125.159, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.1439974749291267e-06, 'batch_size': 32, 'num_epochs': 3, 'threshold': 0.13813501017161417, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5025825076070843, 'eval_precision': 0.511350204576451, 'eval_recall': 0.5171335744498253, 'eval_f1': 0.5142256289907194, 'eval_loss': 3.548862934112549, 'eval_runtime': 64.3414, 'eval_samples_per_second': 996.015, 'eval_steps_per_second': 124.508, 'epoch': 3.0}
Training with parameters: {'learning_rate': 2.9621516588303503e-05, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.4587399872866511, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5078879613013966, 'eval_precision': 0.514536668713458, 'eval_recall': 0.5907251884999694, 'eval_f1': 0.5500049940784498, 'eval_loss': 3.1612648963928223, 'eval_runtime': 64.4866, 'eval_samples_per_second': 993.772, 'eval_steps_per_second': 124.227, 'epoch': 2.0}
Training with parameters: {'learning_rate': 4.12320653261873e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.26856070581242847, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5046266677069517, 'eval_precision': 0.5125692738387705, 'eval_recall': 0.5499601544780237, 'eval_f1': 0.5306068133427964, 'eval_loss': 2.609308958053589, 'eval_runtime': 64.0091, 'eval_samples_per_second': 1001.186, 'eval_steps_per_second': 125.154, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.8410729205738687e-06, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.4587399872866511, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.505188421627526, 'eval_precision': 0.5145433760955164, 'eval_recall': 0.49665910623429166, 'eval_f1': 0.5054430893040955, 'eval_loss': 3.228686571121216, 'eval_runtime': 64.2977, 'eval_samples_per_second': 996.693, 'eval_steps_per_second': 124.592, 'epoch': 2.0}
Training with parameters: {'learning_rate': 1.7258215396625017e-06, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.4256176498949491, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5047358976359523, 'eval_precision': 0.5140281511940534, 'eval_recall': 0.4980996751057439, 'eval_f1': 0.5059385750533149, 'eval_loss': 3.8974249362945557, 'eval_runtime': 64.7589, 'eval_samples_per_second': 989.593, 'eval_steps_per_second': 123.705, 'epoch': 4.0}
Training with parameters: {'learning_rate': 1.1439974749291267e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.28658939302939734, 'weight_decay': 0.0}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.505157213076383, 'eval_precision': 0.5147305312016504, 'eval_recall': 0.48945626187703056, 'eval_f1': 0.5017753338570307, 'eval_loss': 2.6570920944213867, 'eval_runtime': 64.0411, 'eval_samples_per_second': 1000.686, 'eval_steps_per_second': 125.092, 'epoch': 2.0}
Training with parameters: {'learning_rate': 3.385226783451977e-06, 'batch_size': 32, 'num_epochs': 2, 'threshold': 0.6178620555253561, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.504111726613092, 'eval_precision': 0.5135143759772792, 'eval_recall': 0.4932262612640226, 'eval_f1': 0.5031658927817645, 'eval_loss': 2.3506064414978027, 'eval_runtime': 63.9759, 'eval_samples_per_second': 1001.705, 'eval_steps_per_second': 125.219, 'epoch': 2.0}
Training with parameters: {'learning_rate': 2.595942550311263e-05, 'batch_size': 16, 'num_epochs': 2, 'threshold': 0.5564710291701385, 'weight_decay': 0.01}

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\190666351.py:98: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Validation metrics: {'eval_accuracy': 0.5037684325505188, 'eval_precision': 0.5130881746359108, 'eval_recall': 0.4956476429841231, 'eval_f1': 0.5042171398281964, 'eval_loss': 3.5355851650238037, 'eval_runtime': 64.3384, 'eval_samples_per_second': 996.061, 'eval_steps_per_second': 124.514, 'epoch': 2.0}
Best F1 Score: 0.6747321834801671
Best Eval Metrics: {'eval_accuracy': 0.5091519076226886, 'eval_precision': 0.5091289285602821, 'eval_recall': 1.0, 'eval_f1': 0.6747321834801671, 'eval_loss': 0.7248985171318054, 'eval_runtime': 64.9805, 'eval_samples_per_second': 986.219, 'eval_steps_per_second': 123.283, 'epoch': 4.0}
Best Parameters: {'learning_rate': 3.5067764992972196e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.14442679104045422, 'weight_decay': 0.0}
Best Threshold: 0.14442679104045422

## Fine Tuning FinBERT using Optimised Hyperparameters on Training Set

In [25]:
# Training on full train set using best hyperparameters
params = best_params
def compute_metrics(eval_pred):
    predictions, labels = eval_pred.predictions, eval_pred.label_ids
    predicted_probabilities = torch.softmax(torch.tensor(predictions), dim=1).numpy()

    # Apply threshold from params
    threshold = params["threshold"]
    predicted_labels = (predicted_probabilities[:, 1] >= threshold).astype(int)

    # Calculate metrics
    precision, recall, f1, _ = precision_recall_fscore_support(labels, predicted_labels, average='binary')
    accuracy = accuracy_score(labels, predicted_labels)

    return {
        'eval_accuracy': accuracy,
        'eval_precision': precision,
        'eval_recall': recall,
        'eval_f1': f1
    }

final_training_args = TrainingArguments(
    output_dir='./train_full_results',
    evaluation_strategy='epoch',
    save_strategy='epoch',
    logging_dir='./train_full_logs',
    logging_steps=10,
    per_device_train_batch_size=params['batch_size'],
    learning_rate=params['learning_rate'],
    num_train_epochs=params['num_epochs'],
    weight_decay=params['weight_decay'],
    load_best_model_at_end=True,
    metric_for_best_model='eval_f1',
    save_total_limit=1
)

final_trainer = Trainer(
    model=model,
    args=final_training_args,
    train_dataset=train_tokenized_df,  # Full train dataset
    eval_dataset=val_tokenized_df,
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

final_trainer.train()
final_eval_metrics = final_trainer.evaluate()
print("Final Validation Metrics:", final_eval_metrics)
print(params)

# Save the fully trained model
final_trainer.save_model("./finbert_train_full_model")
tokenizer.save_pretrained("./finbert_train_full_model")

C:\Users\Tylus\PycharmProjects\QF634_Research_Methods\.venv2\Lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\4136196502.py:37: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  final_trainer = Trainer(

Final Validation Metrics: {'eval_accuracy': 0.5091050947959741, 'eval_precision': 0.5091050947959741, 'eval_recall': 1.0, 'eval_f1': 0.6747112531149507, 'eval_loss': 0.6931940317153931, 'eval_runtime': 64.544, 'eval_samples_per_second': 992.888, 'eval_steps_per_second': 124.117, 'epoch': 4.0}
{'learning_rate': 3.5067764992972196e-05, 'batch_size': 16, 'num_epochs': 4, 'threshold': 0.14442679104045422, 'weight_decay': 0.0}

('./finbert_train_full_model\\tokenizer_config.json',
 './finbert_train_full_model\\special_tokens_map.json',
 './finbert_train_full_model\\vocab.txt',
 './finbert_train_full_model\\added_tokens.json')

## Predicting on Test Set using Fine Tuned Model

In [42]:
# Use the final model to predict on test set
finbert_final_model = BertForSequenceClassification.from_pretrained('./finbert_train_full_model').to(torch.device('cuda'))
finbert_final_model.config.problem_type = "single_label_classification"

def predict_with_threshold(model, dataset, threshold):
    trainer = Trainer(model=model, tokenizer=tokenizer)
    predictions_output = trainer.predict(dataset)
    predictions = predictions_output.predictions
    labels = predictions_output.label_ids  # True labels from the dataset
    predicted_probabilities = torch.softmax(torch.tensor(predictions), dim=1).numpy()
    predicted_labels = (predicted_probabilities[:, 1] >= threshold).astype(int)

    return predicted_probabilities, predicted_labels, labels

# Use the best threshold for predictions
params = {'learning_rate': 1.5067764992972196e-05,
 'batch_size': 16,
 'num_epochs': 2,
 'threshold': 0.5,
 'weight_decay': 0.01}

threshold = params['threshold']
finbert_probabilities, finbert_predicted_labels, test_labels = predict_with_threshold(finbert_final_model, test_tokenized_df, threshold)

# Compute evaluation metrics on the test set
precision, recall, f1, _ = precision_recall_fscore_support(test_labels, finbert_predicted_labels, average='binary')
accuracy = accuracy_score(test_labels, finbert_predicted_labels)

print(f"Test Accuracy: {accuracy}")
print(f"Test Precision: {precision}")
print(f"Test Recall: {recall}")
print(f"Test F1-Score: {f1}")

# Add predictions to the results dataframe
test_df_results['finbert_sentiment_label'] = finbert_predicted_labels
test_df_results

C:\Users\Tylus\AppData\Local\Temp\ipykernel_14560\2987283618.py:6: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(model=model, tokenizer=tokenizer)

Test Accuracy: 0.4831084651424948
Test Precision: 0.4831084651424948
Test Recall: 1.0
Test F1-Score: 0.6514809624474478

,Unnamed: 0,title,source,Date,sentiment_label,Ticker,date,finbert_sentiment_label
0,9704,tranche update on equity residential s equity ...,Capital IQ Buybacks Database,2024-11-04,0,EQR,2024-11-04,1
1,23443,tranche update on ralph lauren corporation s e...,Capital IQ Buybacks Database,2024-08-07,0,RL,2024-08-07,1
2,20426,northern trust corporation presents at barclay...,PR Newswire; Business Wire; GlobeNewswire; Can...,2024-09-10,0,NTRS,2024-09-10,1
3,23009,paypal holdings inc expected to report q3 2024...,Capital IQ Expected Earnings Database,2024-10-29,0,PYPL,2024-10-29,1
4,25698,truist financial corporation announces redempt...,PR Newswire,2024-11-01,0,TFC,2024-11-01,1
...,...,...,...,...,...,...,...,...
28382,22297,palantir technologies inc reports earnings res...,S&P Capital IQ Financials Database,2024-08-05,1,PLTR,2024-08-05,1
28383,5572,charter communications inc announces pricing f...,PR Newswire,2024-05-23,1,CHTR,2024-05-23,1
28384,890,ameren corporation shareholderanalyst call,SEC Filing,2024-05-09,0,AEE,2024-05-09,1
28385,16321,labcorp holdings inc 072 cash dividend nov262024,Financial Times,2024-11-26,0,LH,2024-11-26,1
28386,24433,synopsys inc q3 2024 earnings call aug 21 2024,PR Newswire; Company Website,2024-08-21,0,SNPS,2024-08-21,1

In [13]:
# test_df_results.to_csv("test_df_results.csv", index=False)

C:\Users\Tylus\AppData\Local\Temp\ipykernel_12020\997101882.py:5: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(model=model, tokenizer=tokenizer)

In [ ]:
# # Compute ROC AUC
# roc_auc = roc_auc_score(test_labels, finbert_probabilities[:, 1])
# fpr, tpr, thresholds = roc_curve(test_labels, finbert_probabilities[:, 1])
#
# # Plot the ROC Curve
# plt.figure(figsize=(8, 6))
# plt.plot(fpr, tpr, label=f"ROC Curve (AUC = {roc_auc:.2f})", linewidth=2)
# plt.plot([0, 1], [0, 1], 'k--', label="Random Guess", linewidth=2)
# plt.title("ROC Curve", fontsize=16)
# plt.xlabel("False Positive Rate (FPR)", fontsize=14)
# plt.ylabel("True Positive Rate (TPR)", fontsize=14)
# plt.legend(loc="lower right", fontsize=12)
# plt.grid(True)
# plt.show()
#
# print(f"ROC AUC Score: {roc_auc}")